### ISSUE TITLE
Cannot install into Beanstlak Linux 2

### ISSUE THREAD

**Issue by ricsands2801** [awslabs/aws-crt-php#109]
### Describe the bug

trying to install via pecl install and get error;

```
running: make
which: no cmake3 in (/root/pear:/root/.local/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/snapd/snap/bin)
cmake -DCMAKE_SOURCE_DIR=/root/pear/temp/awscrt -DCMAKE_BINARY_DIR=./cmake_build -DCMAKE_INSTALL_PREFIX=./build/install -DBUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUSE_OPENSSL=ON  -H/root/pear/temp/awscrt/crt/aws-crt-ffi -B./cmake_build/aws-crt-ffi-static -DBUILD_SHARED_LIBS=OFF
make: cmake: No such file or directory
make: *** [Makefile:25
```

How can we install into linux 2?

### Expected Behavior

to install

### Current Behavior

Getting error

### Reproduction Steps

Run pecl install awscrt in linux 2 beanstalk

### aws-crt-php version used

latest

### php version used

8.2

### Operating System and version

linux 2

**Comment by TingDaoK** [comment]
you need cmake installed in your environment as the [requirement](https://github.com/awslabs/aws-crt-php?tab=readme-ov-file#requirements).
