### ISSUE TITLE
conflict "phpunit/php-timer": ">=2"

### ISSUE THREAD

**Issue by pascallap** [awslabs/aws-crt-php#47]
Confirm by changing [ ] to [x] below:
- [x] I've searched for [previous similar issues](https://github.com/awslabs/aws-crt-php/issues) and didn't find any solution

**Describe the question**
This module is now used by aws-sdk-php (version 3.192.0). Is there a good reason why phpunit/php-timer is listed has a conflict for version higher than 2?

Phpunit 8 and Phpunit 9 are the supported versions for current version of php and they require newer version of phpunit/php-timer.

**Logs/output**
composer update on our project that require aws-php-sdk:

Problem 1
    - phpunit/phpunit[9.4.1, ..., 9.5.9] require phpunit/php-timer ^5.0.2 -> satisfiable by phpunit/php-timer[5.0.2, 5.0.3].
    - phpunit/phpunit[9.2.6, ..., 9.4.0] require phpunit/php-timer ^5.0.1 -> satisfiable by phpunit/php-timer[5.0.1, 5.0.2, 5.0.3].
    - phpunit/phpunit[9.2.2, ..., 9.2.5] require phpunit/php-timer ^5.0 -> satisfiable by phpunit/php-timer[5.0.0, 5.0.1, 5.0.2, 5.0.3].
    - phpunit/phpunit[9.2.0, ..., 9.2.1] require phpunit/php-timer ^4.0 -> satisfiable by phpunit/php-timer[4.0.0].
    - phpunit/phpunit[9.1.2, ..., 9.1.5] require phpunit/php-timer ^3.1.4 -> satisfiable by phpunit/php-timer[3.1.4].
    - phpunit/phpunit[9.0.0, ..., 9.1.1] require phpunit/php-timer ^3.0 -> satisfiable by phpunit/php-timer[3.0.0, ..., 3.1.4].
    - aws/aws-crt-php 1.0.1 conflicts with phpunit/php-timer 5.0.3.
    - aws/aws-crt-php 1.0.1 conflicts with phpunit/php-timer 5.0.2.
    - aws/aws-crt-php 1.0.1 conflicts with phpunit/php-timer 5.0.1.
    - aws/aws-crt-php 1.0.1 conflicts with phpunit/php-timer 5.0.0.
    - aws/aws-crt-php 1.0.1 conflicts with phpunit/php-timer 4.0.0.
    - aws/aws-crt-php 1.0.1 conflicts with phpunit/php-timer 3.1.4.
    - aws/aws-crt-php 1.0.1 conflicts with phpunit/php-timer 3.1.3.
    - aws/aws-crt-php 1.0.1 conflicts with phpunit/php-timer 3.1.2.
    - aws/aws-crt-php 1.0.1 conflicts with phpunit/php-timer 3.1.1.
    - aws/aws-crt-php 1.0.1 conflicts with phpunit/php-timer 3.1.0.
    - aws/aws-crt-php 1.0.1 conflicts with phpunit/php-timer 3.0.0.
    - aws/aws-sdk-php 3.192.0 requires aws/aws-crt-php ^1.0.1 -> satisfiable by aws/aws-crt-php[1.0.1].
    - Root composer.json requires aws/aws-sdk-php ^3.147, 3.192.0 -> satisfiable by aws/aws-sdk-php[3.192.0].
    - Root composer.json requires phpunit/phpunit ^9 -> satisfiable by phpunit/phpunit[9.0.0, ..., 9.5.9].

**Comment by kevinpurwito** [comment]
as a temporary solution, you can instead use the previous version of AWS SDK

```
composer require aws/aws-sdk-php:~3.191
```

**Comment by pascallap** [comment]
Thanks @kevinpurwito this is exactly what we are doing right now. 

But we have a system that checks that all our dependencies are updated to the minor patch level. 
`composer outdated -m --direct --locked --no-dev`
And in this case, it always flags this dependency as lagging behind.

So for the time being, we are manually skipping this check...

**Comment by pascallap** [comment]
The problem is solved with version 1.0.2 thanks!
