### ISSUE TITLE
Loading ASW S3 not loading

### ISSUE THREAD

**Issue by juggernautsei** [awslabs/aws-crt-php#67]
Confirm by changing [ ] to [x] below:
- [x ] I've searched for [previous similar issues](https://github.com/awslabs/aws-crt-php/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?
AWS
Ubuntu 20.04
t3 small

**Describe the question**
After the build and putting the path to the .so file in the php.ini file. My script page to upload a test file to my S3 bucket will not load. 

**Logs/output**
If applicable, add logs or error output.

My log error is:
AH00051: child pid 5600 exit signal Segmentation fault (11), possible coredump in /etc/apache2

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

**Comment by juggernautsei** [comment]
Here is the build information.


----------------------------------------------------------------------
Libraries have been installed in:
   /var/www/html/mindful_610/interface/modules/custom_modules/oe-simple-storage-solution/vendor/aws-crt-php/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,--rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------

Build complete.
Don't forget to run 'make test'.


Build complete.
Don't forget to run 'make test'.

composer run test-extension
> ./run_tests
+ launcher=
+ command -v catchsegv
+ launcher=catchsegv
+ '[' -z /usr/bin/php7.4 ']'
/usr/bin/catchsegv
+ '[' '!' -d vendor ']'
+ catchsegv /usr/bin/php7.4 -c php.ini vendor/bin/phpunit tests --debug
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.


Starting test 'CoreTest::testIsAvailable'.
.
Starting test 'CoreTest::testIsLoaded'.
.
Starting test 'CrcTest::testCrc32ZeroesOneShot'.
.
Starting test 'CrcTest::testCrc32ZeroesIterated'.
.
Starting test 'CrcTest::testCrc32ValuesOneShot'.
.
Starting test 'CrcTest::testCrc32ValuesIterated'.
.
Starting test 'CrcTest::testCrc32LargeBuffer'.
.
Starting test 'CrcTest::testCrc32cZeroesOneShot'.
.
Starting test 'CrcTest::testCrc32cZeroesIterated'.
.
Starting test 'CrcTest::testCrc32cValuesOneShot'.
.
Starting test 'CrcTest::testCrc32cValuesIterated'.
.
Starting test 'CrcTest::testCrc32cLargeBuffer'.
.
Starting test 'CredentialsTest::testEmptyCredentials'.
.
Starting test 'CredentialsTest::testCredentialsLifetime'.
.
Starting test 'CredentialsTest::testStaticCredentialsProviderLifetime'.
.
Starting test 'ErrorTest::testNoInitialError'.
.
Starting test 'ErrorTest::testCanResolveErrorName'.
.
Starting test 'ErrorTest::testCanResolveErrorStr'.
.
Starting test 'EventLoopGroupTest::testLifetime'.
.
Starting test 'EventLoopGroupTest::testConstructionWithOptions'.
.
Starting test 'HttpMessageTest::testHeaders'.
.
Starting test 'HttpMessageTest::testHeadersMarshalling'.
.
Starting test 'HttpMessageTest::testRequestMarshalling'.
.
Starting test 'HttpMessageTest::testRequestMarshallingWithQueryParams'.
.
Starting test 'HttpMessageTest::testResponseMarshalling'.
.
Starting test 'LogTest::testLogToStream'.
.
Starting test 'SigningTest::testConfigAWSLifetime'.
.
Starting test 'SigningTest::testConfigAWSConstructionWithOptions'.
.
Starting test 'SigningTest::testSignableFromHttpRequestLifetime'.
.
Starting test 'SigningTest::testSignableFromChunkLifetime'.
.
Starting test 'SigningTest::testSignableFromCanonicalRequestLifetime'.
.
Starting test 'SigningTest::testShouldSignHeader'.
.
Starting test 'SigningTest::testSigv4HeaderSigning'.
.
Starting test 'SigningTest::testSigV4aHeaderSigning'.
.
Starting test 'InputStreamTest::testMemoryStream'.
.                               35 / 35 (100%)

Time: 700 ms, Memory: 68.01MB

OK (35 tests, 74 assertions)


-------------------------------------------------------------------------------------------------------------------
PHP         : /usr/bin/php7.4
PHP_SAPI    : cli
PHP_VERSION : 7.4.3
ZEND_VERSION: 3.4.0
PHP_OS      : Linux - Linux ip-172-31-6-118 5.15.0-1015-aws #19~20.04.1-Ubuntu SMP Wed Jun 22 19:07:51 UTC 2022 x86_64
INI actual  : /var/www/html/mindful_610/interface/modules/custom_modules/oe-simple-storage-solution/vendor/aws-crt-php/tmp-php.ini
More .INIs  :
CWD         : /var/www/html/mindful_610/interface/modules/custom_modules/oe-simple-storage-solution/vendor/aws-crt-php
Extra dirs  :
VALGRIND    : Not used
----------------------------------------------------------------------------------------------------
TIME START 2022-08-08 04:54:46
----------------------------------------------------------------------------------------------------

**Comment by jmklix** [comment]
Can you try updating to the latest version? We have fixed some seg fault issues since this issue was opened
