### ISSUE TITLE
Error "No rule to make target 'install'.  Stop." when executing make.

### ISSUE THREAD

**Issue by andrecarlucci** [awslabs/aws-crt-php#80]
Confirm by changing [ ] to [x] below to ensure that it's a bug:

- [x ] I've gone though [Developer Guide](https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/welcome.html) and [API reference](http://sdk.amazonaws.com/cpp/api/LATEST/index.html)
- [ x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-cpp/issues) and didn't find any solution
  
**Describe the bug**
I'm trying to install the SDK on Lightsail WordPress Certified by Bitnami and Automattic 6.1.1-13 box.

Executed the following commands:
$ git clone --recursive https://github.com/awslabs/aws-crt-php.git
$ cd aws-crt-php
$ phpize
$ ./configure
$ make && make test

They all worked but the last one (make).
This is the output:
```
bitnami@ip-some-ip:~/stack/aws-crt-php$ make && make test
CMAKE_BUILD_PARALLEL_LEVEL='' cmake --build build/aws-crt-ffi-static --config RelWithDebInfo --target install
gmake[1]: Entering directory '/opt/bitnami/aws-crt-php/build/aws-crt-ffi-static'
gmake[1]: *** No rule to make target 'install'.  Stop.
gmake[1]: Leaving directory '/opt/bitnami/aws-crt-php/build/aws-crt-ffi-static'
make: *** [Makefile:244: build/aws-crt-ffi-static/libaws-crt-ffi.a] Error 2
bitnami@ip-some-ip:~/stack/aws-crt-php$ 
```

This is my folder:
```
bitnami@ip-some-ip:~/stack/aws-crt-php$ ls
autom4te.cache      config.h.in    configure.ac     gen_api.php   Makefile.frag       package.xml-template_post  README.md
build               config.log     config.w32       gen_stub.php  Makefile.fragments  package.xml-template_pre   run_tests
builder.json        config.m4      CONTRIBUTING.md  include       Makefile.frag.w32   php.ini                    run_tests.bat
CODE_OF_CONDUCT.md  config.nice    crt              libtool       Makefile.objects    php-win.ini                run-tests.php
composer.json       config.status  ext              LICENSE       modules             prepare_package_xml.sh     src
config.h            configure      format-check.sh  Makefile      NOTICE              prepare_release.sh         tests
bitnami@ip-some-ip:~/stack/aws-crt-php$ 
```
Any help is appreciated :)

**Comment by TingDaoK** [comment]
Not have clear idea, totally throw possible ideas that may help to locate the issue: 
- Do you have Cmake installed? 
- What version of aws-crt-php you are using?
- If possible, can you post the `Makefile` detail?

The log from make should look like, you can check from our [CI](https://github.com/awslabs/aws-crt-php/actions/runs/4285076300/jobs/7462904045#step:4:134):
```
cmake -DCMAKE_INSTALL_PREFIX=build/install -DBUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUSE_OPENSSL=ON  -Hcrt/aws-crt-ffi -Bbuild/aws-crt-ffi-static -DBUILD_SHARED_LIBS=OFF
-- The C compiler identification is Clang 14.0.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- CMake 3.25.2
-- CMake 3.25.2
```

**Comment by yasminetalby** [comment]
Hello @andrecarlucci ,

I hope that you are doing well. Do you still need support regarding this issue or can this issue be closed?

Best regards,

Yasmine

**Comment by yasminetalby** [comment]
Hello,
I am closing this issue as there was no updates since the submission. If you still need support you can open a new issue within our repository.

Thank you very much for your time and collaboration.

Sincerely,

Yasmine
