### ISSUE TITLE
PHP 5.x compatibility - undefined symbol: zend_error_noreturn

### ISSUE THREAD

**Issue by remicollet** [awslabs/aws-crt-php#95]
Since 1.2.0,  package.xml states **5.5** is supported

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/builddir/build/BUILDROOT/php-pecl-awscrt-1.2.0-1.el7.remi.5.5.x86_64//usr/lib64/php/modules/awscrt.so' - /builddir/build/BUILDROOT/php-pecl-awscrt-1.2.0-1.el7.remi.5.5.x86_64//usr/lib64/php/modules/awscrt.so: undefined symbol: zend_error_noreturn in Unknown on line 0
```

`zend_error_noreturn` was introduced, as **public** API in PHP **7.0**

**Comment by TingDaoK** [comment]
We do run tests for php 5.6, [here](https://github.com/awslabs/aws-crt-php/actions/runs/4452121081/jobs/7819490177?pr=97)

But, yeah, seems like we have issue for php5.5

**Comment by remicollet** [comment]
> We do run tests for php 5.6, [here](https://github.com/awslabs/aws-crt-php/actions/runs/4452121081/jobs/7819490177?pr=97)

PHP 5.6 is also affected
See explanation on pr #96

**Comment by TingDaoK** [comment]
I mean we have test for php5.6, that builds and runs the code. But, I see your fix should be needed for php 5.x, just kind wander why it's not caught by our CI for php5.6.

**Comment by remicollet** [comment]
> I mean we have test for php5.6, that builds and runs the code. But, I see your fix should be needed for php 5.x, just kind wander why it's not caught by our CI for php5.6.

- perhaps php build doesn't-have the default "visibility = hidden" option
- perhaps the call is not covered by the tests

Real builds (packages) for real distributions use lot of security build options.

**Comment by TingDaoK** [comment]
>  + /usr/bin/php --version
PHP 5.5.38 (cli) (built: Feb 12 2023 11:38:56) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans

I printed `php --version` from our CI that used [shivammathur/setup-php](https://github.com/shivammathur/setup-php) to setup the exact version of php. I still cannot reproduce the issue with CI.

I did reproduced it from my local linux machine that used php55 from [here](https://blog.remirepo.net/), with that I also printed the version of php, which is:
```
php55 --version
PHP 5.5.38 (cli) (built: Jun 23 2022 08:01:11) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
```

could that be related to `with Zend OPcache v7.0.6-dev`?

**Comment by remicollet** [comment]
No this is related to PHP build options used in Linux distribution for security and performance.

See: https://github.com/php/php-src/blob/PHP-7.0/Zend/zend.h#L86  this is in public API (ZEND_API)
See: https://github.com/php/php-src/blob/PHP-5.5/Zend/zend.h#L294 this is not public

**Comment by TingDaoK** [comment]
Okay, I see. I tried to install php using `ondrej/php`, which is used by setup-php action [here](https://github.com/shivammathur/setup-php/blob/master/src/scripts/linux.sh#L79).

Now, I cannot reproduce that error.

Yeah, I think it's very likely that php build doesn't-have the default "visibility = hidden" option. :)

I'll create an issue to [shivammathur/setup-php](https://github.com/shivammathur/setup-php) and see if they can fix it in order to catch this kind of issue from our CI.

**Comment by TingDaoK** [comment]
the new 1.2.1 version should solve the issue. https://pecl.php.net/package/awscrt/1.2.1
